name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
  # schedule: [cron: "40 1 * * *"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  ZIG: "0.13.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG }}
      - run: zig build --verbose --summary all --color on
      - run: zig build test --verbose --summary all --color on
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG }}
      - run: zig fmt --check ./
