name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
  schedule: [cron: "40 1 * * *"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  ZIG: 0.12.0+147beec7d

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG }}
      - run: zig build test
