name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
  schedule: [cron: "40 1 * * *"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  ZIG: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG }}
      - run: zig build
      - run: zig build test
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG }}
      - run: zig fmt --check ./
